import { expect, type APIRequestContext, type Page, type TestInfo } from '@playwright/test';
import { connect, fixtureUrl, openChatList, operationCount, screenshot, state } from './chat-helpers';

export async function modelPickerJourney(page: Page, request: APIRequestContext, info: TestInfo) {
  await connect(page);
  await expect(page.getByRole('status').filter({ hasText: /P2P|Relay/ })).toBeVisible();
  const input = page.getByRole('textbox', { name: '聊天消息' });
  await input.fill('保留模型设置时的草稿');
  const trigger = page.getByRole('button', { name: /^模型与推理强度：/ });
  await trigger.click();
  const panel = page.getByRole('dialog', { name: '模型与推理强度', exact: true });
  await expect(panel).toBeVisible();
  expect((await panel.boundingBox())!.width).toBeLessThanOrEqual(226);
  await expect(page.getByRole('dialog', { name: '聊天设置', exact: true })).toHaveCount(0);
  const slider = page.getByRole('slider', { name: '推理强度', exact: true });
  await slider.press('End');
  await expect(slider).toHaveAttribute('aria-valuetext', '极高');
  await expect.poll(async () => (await state(request)).composer.settings.effort).toBe('xhigh');
  await screenshot(page, info, 'desktop-reasoning-picker');
  await page.getByRole('button', { name: '恢复推荐推理强度' }).click();
  await expect.poll(async () => (await state(request)).composer.settings.effort).toBe('medium');
  await expect(page.getByRole('button', { name: '恢复推荐推理强度' })).toBeDisabled();
  await request.post(`${fixtureUrl}/test/settings-delay`, { data: { milliseconds: 1200 } });
  await slider.press('ArrowRight');
  await expect(slider).toBeEnabled();
  await slider.press('End');
  await expect(slider).toHaveAttribute('aria-valuetext', '极高');
  await expect.poll(async () => (await state(request)).composer.settings.effort).toBe('xhigh');
  await request.post(`${fixtureUrl}/test/settings-delay`, { data: { milliseconds: 0 } });
  await page.getByRole('button', { name: '选择模型', exact: true }).click();
  const first = page.getByRole('menuitemradio', { name: '测试模型', exact: true });
  const second = page.getByRole('menuitemradio', { name: '第二模型', exact: true });
  await expect(first).toBeFocused();
  await first.press('ArrowDown');
  await expect(second).toBeFocused();
  await screenshot(page, info, 'desktop-model-list');
  await second.press('Enter');
  await expect(slider).toHaveAttribute('aria-valuetext', '中');
  await expect.poll(async () => (await state(request)).composer.settings.model).toBe('second-model');
  await request.post(`${fixtureUrl}/test/composer`, { data: { effort: 'xhigh' } });
  await expect(slider).toHaveAttribute('aria-valuetext', '极高');
  await slider.press('Escape');
  await expect(panel).not.toBeVisible();
  await expect(trigger).toBeFocused();
  await expect(input).toHaveValue('保留模型设置时的草稿');
  expect(await operationCount(request, 'send')).toBe(0);
  await trigger.click();
  await openChatList(page);
  await page.getByRole('button', { name: '移动端聊天体验', exact: true }).click();
  await expect(panel).not.toBeVisible();
  await trigger.click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(panel).toHaveCount(0);
  await page.getByRole('button', { name: /聊天设置/ }).click();
  await expect(page.getByRole('button', { name: '设置推理强度' })).toBeVisible();
  await expect(slider).toHaveCount(0);
  await screenshot(page, info, 'mobile-settings-unchanged');
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(page.getByRole('dialog', { name: '聊天设置', exact: true })).toHaveCount(0);
  await expect(trigger).toBeVisible();
}
