import { StyleSheet } from 'react-native';

export const totpStyles = StyleSheet.create({
  empty: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#dce8df',
    borderRadius: 15,
    backgroundColor: '#f7faf7',
    padding: 24,
  },
  emptyIcon: { color: '#18af8c', fontSize: 32, fontWeight: '900' },
  emptyTitle: { color: '#13231c', fontSize: 16, fontWeight: '800', marginTop: 10 },
  emptyText: { color: '#6f8177', fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 },
  codeCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    padding: 18,
    marginBottom: 15,
    shadowColor: '#397b61',
    shadowOpacity: 0.04,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  codeHeader: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  codeIdentity: { flex: 1, minWidth: 0 },
  issuer: { color: '#101827', fontSize: 16, fontWeight: '700' },
  account: { color: '#9299a6', fontSize: 13, marginTop: 3 },
  moreButton: { minWidth: 32, minHeight: 44, alignItems: 'center', justifyContent: 'center', marginRight: -8 },
  codeBody: { flexDirection: 'row', alignItems: 'center', gap: 22, marginTop: 13 },
  compactCodeBody: { gap: 12 },
  codeButton: { flex: 1, minWidth: 0 },
  codeRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6 },
  codeValue: { flex: 1, color: '#008956', fontSize: 36, fontWeight: '800', fontVariant: ['tabular-nums'] },
  countdown: { color: '#7b8390', fontSize: 12, fontWeight: '500' },
  progressTrack: { height: 7, overflow: 'hidden', borderRadius: 4, backgroundColor: '#e8edf1', marginTop: 8 },
  progressFill: { height: '100%', borderRadius: 4, backgroundColor: '#40b28e' },
  copyButton: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7,
    minHeight: 40, paddingHorizontal: 13, paddingVertical: 8, borderRadius: 11, backgroundColor: '#e5f5ee',
  },
  copyText: { color: '#008956', fontSize: 15, fontWeight: '700' },
  compactCopyButton: { minWidth: 44, paddingHorizontal: 8 },
  pressed: { opacity: 0.65 },
  fieldLabel: { color: '#13231c', fontSize: 13, fontWeight: '700', marginBottom: 7, marginTop: 13 },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#cbdcd0',
    borderRadius: 10,
    backgroundColor: '#fbfdfb',
    color: '#13231c',
    fontSize: 15,
    paddingHorizontal: 13,
  },
  secretRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  secretInput: { flex: 1 },
  revealButton: { minHeight: 46, justifyContent: 'center', paddingHorizontal: 12 },
  revealText: { color: '#14806f', fontSize: 12, fontWeight: '800' },
  hint: { color: '#6f8177', fontSize: 11, lineHeight: 17, marginTop: 6 },
  qrButton: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#e8f8fb',
    marginBottom: 4,
  },
  qrButtonText: { color: '#168da2', fontSize: 14, fontWeight: '800' },
  error: { color: '#bd3c35', fontSize: 12, lineHeight: 18, marginTop: 10 },
  optionRow: { flexDirection: 'row', gap: 8 },
  option: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#eef3f0',
  },
  optionActive: { backgroundColor: '#d8f4ec', borderWidth: 1, borderColor: '#8fdcca' },
  optionText: { color: '#6f8177', fontSize: 12, fontWeight: '700' },
  optionTextActive: { color: '#0b8065' },
  formScroll: { maxHeight: 570 },
  formContent: { paddingBottom: 8 },
  cameraRoot: { flex: 1, backgroundColor: '#06140f' },
  camera: { flex: 1 },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 28,
  },
  cameraTitle: { color: '#fff', fontSize: 20, fontWeight: '900', marginTop: 36 },
  scanFrame: { width: 260, height: 260, borderWidth: 3, borderColor: '#a7e733', borderRadius: 24 },
  cameraHint: { color: '#fff', fontSize: 13, lineHeight: 19, textAlign: 'center' },
  cameraClose: {
    minWidth: 120,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: '#ffffff',
  },
  cameraCloseText: { color: '#13231c', fontSize: 15, fontWeight: '800' },
  permissionBox: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, backgroundColor: '#f7faf7' },
  permissionTitle: { color: '#13231c', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  permissionText: { color: '#6f8177', fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 9 },
});
